languages:
  Ruby: true
  JavaScript: true
  PHP: true
  Python: true
exclude_paths:
- "pets/functional_tests/*"
- "pets/meupet/tests/*"
- "pets/users/tests.py"
- "pets/common/migrations/*"
- "pets/meupet/migrations/*"
- "pets/users/migrations/*"