# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-15 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meupet', '0033_remove_status_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='new_status',
            new_name='status',
        ),
    ]
